include_recipe "redisio::_install_build_packages"
include_recipe "redisio::_install_from_source"
include_recipe "redisio::_create_user"
include_recipe "redisio::_create_directories"
include_recipe "redisio::_set_overcommit_memory"
